apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discord-bot.fullname" . }}
  labels:
    {{- include "discord-bot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "discord-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "discord-bot.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.token.name }}
                key: {{ .Values.secrets.token.key }}
          - name: CLIENT_ID
            value: {{ .Values.env.clientId }}
          - name: REDIS_URL
            value: redis://discord-bot-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379
          - name: NODE_ENV
            value: "production"
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.sentryDsn.name }}
                key: {{ .Values.secrets.sentryDsn.key }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}