apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "discord-bot.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "discord-bot.fullname" . }}
spec:
  storageClassName: "{{ .Values.persistentVolumeClaim.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.persistentVolumeClaim.size }}"