{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "discord-bot.fullname" . }}-binding
  labels:
    {{- include "discord-bot.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "discord-bot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "discord-bot.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }} 