apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wicek.fullname" . }}
  labels:
    {{- include "wicek.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wicek.fullname" . }}-claude
  labels:
    {{- include "wicek.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
