apiVersion: v2
name: wicek
description: Minimal Claude Code agent with Discord bot interface
home: https://github.com/xxczaki/wicek
keywords:
  - claude-code
  - discord-bot
  - ai-agent
maintainers:
  - name: Antoni Kepinski
    url: https://github.com/xxczaki
sources:
  - https://github.com/xxczaki/charts/tree/main/charts/wicek
type: application
version: 0.1.105
appVersion: "262d5ee18a5f1653829a4725bbf7c4645b234f48"
