apiVersion: v2
name: wicek
description: Minimal Claude Code agent with Discord bot interface
home: https://github.com/xxczaki/wicek
keywords:
  - claude-code
  - discord-bot
  - ai-agent
maintainers:
  - name: Antoni Kepinski
    url: https://github.com/xxczaki
sources:
  - https://github.com/xxczaki/charts/tree/main/charts/wicek
type: application
version: 0.1.254
appVersion: "d8c45a6021b12e8c84ad5378db099b4446078346"
