name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          git-push: true